### PR TITLE
Station seed

### PR DESCRIPTION
**Pull request by israelst**
Create and document station initial data load.

### CODE REVIEW

**Comment by israelst** [comment]
Related to #4

**Comment by fccoelho** [comment]
@israelst, It would be nice to replace, in the csv, the name of the city by the official, unicode, name available in the "Dengue_global"."Municipio" table. This way, we can query for all stations in a given municipality. You can do that by checking which municipio contains the coordinate. This can be accomplished through the method `contains` or `within` from [shapely](http://toblerity.org/shapely/manual.html#predicates-and-relationships).

**Comment by israelst** [comment]
It would be great! Can we create a issue and postpone this implementation in favor of deploy the automated WU capture?

**Comment by fccoelho** [comment]
Sure, let's create an issue. The capture is our priority.we can always do an alter table later.

**Pull request merged**
