### PR TITLE
Bugfix/data setup

### PR DESCRIPTION
**Pull request by israelst**

### CODE REVIEW

**Comment by fccoelho** [comment]
Seems Ok. though it may be a good Idea to make sure the `dengue.sql` matches the schema of the current production database.

**Comment by israelst** [comment]
@fccoelho It was generated by `pg_dump -OsC dengue`.

**Comment by flavioamieiro** [comment]
Thank you very much @israelst . This makes it a lot easier for people looking at the code for the first time. This fixes #17 as far as I can tell.

**Comment by fccoelho** [comment]
I think it can be safely merged. @flavioamieiro , can you merge it?

**Comment by flavioamieiro** [comment]
Done!

**Pull request merged**
